import type { UserProfile, Shipment } from "./types";

export const users: UserProfile[] = [
  {
    uid: "admin01",
    name: "Admin User",
    email: "admin@trucktrack.com",
    role: "admin",
  },
  {
    uid: "driver01",
    name: "John Doe",
    email: "john.doe@trucktrack.com",
    role: "driver",
  },
  {
    uid: "driver02",
    name: "Jane Smith",
    email: "jane.smith@trucktrack.com",
    role: "driver",
  },
];

export const shipments: Shipment[] = [
  {
    id: "ship001",
    orderCode: "TT-A4B6C8",
    assignedDriverId: "driver01",
    assignedDriverName: "John Doe",
    createdAt: new Date("2024-07-28T08:00:00Z").toISOString(),
    updatedAt: new Date("2024-07-28T14:30:00Z").toISOString(),
    currentStatus: "departed_warehouse",
    statusTimestamps: {
      arrived_at_warehouse: new Date("2024-07-28T09:15:00Z").toISOString(),
      start_loading: new Date("2024-07-28T09:45:00Z").toISOString(),
      end_loading: new Date("2024-07-28T11:00:00Z").toISOString(),
      departed_warehouse: new Date("2024-07-28T11:30:00Z").toISOString(),
    },
    isCompleted: false,
    origin: "Warehouse A, Los Angeles",
    destination: "Distribution Center, Phoenix",
    statusLogs: [
      {
        id: "log001",
        status: "arrived_at_warehouse",
        timestamp: new Date("2024-07-28T09:15:00Z").toISOString(),
        actorId: "driver01",
        actorName: "John Doe",
        source: "driver",
      },
      {
        id: "log002",
        status: "start_loading",
        timestamp: new Date("2024-07-28T09:45:00Z").toISOString(),
        actorId: "driver01",
        actorName: "John Doe",
        source: "driver",
      },
      {
        id: "log003",
        status: "end_loading",
        timestamp: new Date("2024-07-28T11:00:00Z").toISOString(),
        actorId: "driver01",
        actorName: "John Doe",
        source: "driver",
      },
      {
        id: "log004",
        status: "departed_warehouse",
        timestamp: new Date("2024-07-28T11:30:00Z").toISOString(),
        actorId: "driver01",
        actorName: "John Doe",
        source: "driver",
      },
    ],
  },
  {
    id: "ship002",
    orderCode: "TT-D9E2F1",
    assignedDriverId: "driver02",
    assignedDriverName: "Jane Smith",
    createdAt: new Date("2024-07-29T10:00:00Z").toISOString(),
    updatedAt: new Date("2024-07-29T10:00:00Z").toISOString(),
    currentStatus: "pending",
    statusTimestamps: {},
    isCompleted: false,
    origin: "Factory, Detroit",
    destination: "Retail Hub, Chicago",
    statusLogs: [],
  },
  {
    id: "ship003",
    orderCode: "TT-G7H3I5",
    assignedDriverId: "driver01",
    assignedDriverName: "John Doe",
    createdAt: new Date("2024-07-27T12:00:00Z").toISOString(),
    updatedAt: new Date("2024-07-28T18:00:00Z").toISOString(),
    currentStatus: "trip_completed",
    statusTimestamps: {
      arrived_at_warehouse: new Date("2024-07-27T13:00:00Z").toISOString(),
      start_loading: new Date("2024-07-27T13:30:00Z").toISOString(),
      end_loading: new Date("2024-07-27T14:30:00Z").toISOString(),
      departed_warehouse: new Date("2024-07-27T15:00:00Z").toISOString(),
      arrived_at_destination: new Date("2024-07-28T17:00:00Z").toISOString(),
      delivered: new Date("2024-07-28T17:45:00Z").toISOString(),
      trip_completed: new Date("2024-07-28T18:00:00Z").toISOString(),
    },
    isCompleted: true,
    origin: "Port of Miami",
    destination: "Client Warehouse, Orlando",
    statusLogs: [
        { id: 'log1', status: 'arrived_at_warehouse', timestamp: new Date('2024-07-27T13:00:00Z').toISOString(), actorId: 'driver01', actorName: 'John Doe', source: 'driver' },
        { id: 'log2', status: 'start_loading', timestamp: new Date('2024-07-27T13:30:00Z').toISOString(), actorId: 'driver01', actorName: 'John Doe', source: 'driver' },
        { id: 'log3', status: 'end_loading', timestamp: new Date('2024-07-27T14:30:00Z').toISOString(), actorId: 'driver01', actorName: 'John Doe', source: 'driver' },
        { id: 'log4', status: 'departed_warehouse', timestamp: new Date('2024-07-27T15:00:00Z').toISOString(), actorId: 'driver01', actorName: 'John Doe', source: 'driver' },
        { id: 'log5', status: 'arrived_at_destination', timestamp: new Date('2024-07-28T17:00:00Z').toISOString(), actorId: 'driver01', actorName: 'John Doe', source: 'driver' },
        { id: 'log6', status: 'delivered', timestamp: new Date('2024-07-28T17:45:00Z').toISOString(), actorId: 'driver01', actorName: 'John Doe', source: 'driver' },
        { id: 'log7', status: 'trip_completed', timestamp: new Date('2024-07-28T18:00:00Z').toISOString(), actorId: 'driver01', actorName: 'John Doe', source: 'driver' },
    ],
  },
];
